rvm:
- 2.1.7
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
script: make travis
after_success: make travis_success
env:
  global:
  # GitHub Pages
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.com
  - secure: j9hUCLbjQu6S/WsOJDyL3/ErccQS/tGK4VfKbAYrg0BYGp5RUdGEhjvCB6nhHZHbmKqFERKWuhJeXXTYoZg2RFE2jBqheDPYAp7H0Glu1gt4ev/+aEDI6/G69nOddfbFqDudRAHA2bpOGKbpsEcG9AI5pTGPEu0hyqL+KacpwK3Fl7ReyPGBLRcZ8XEHVH1+Dxaa2JgDZKx3yKWbRJbgJvYkufR/Kh1H84tAInLj0Yead+C1VZVsCfMwSm3LdNLWCzkMqqxoUERnKz+OpJHWLZtDPW94wEYEwx5C7u0jibtTSGImxCt8MUMm8HgnzvWzT/LOYwF7htQpvTHHboswPzGz/JXTCe8MqELWK6MNGFqOqw8VI1qzrCRAUeM32Q5EA9D5MihzTIcYzb0RbJkS41QWRb8BZ+0Xx00ygfHMEH1+9B1aZBz4IK5ap5jRylYDlIqffbxvHJcZRottJai303c2r/ZmSGJJjxh74MkKmCoFJcac0XRqYEhNd7PYhIOdan+DzSeiMd5K6wqwhAtcM2RpijyimQGkHaC6CyJavEWebIzD0a+gXrTpXEd1HmaFNUdpq8KyBcYBBT1HrMdoJT+7KTLgvea2CslCPzHroZftLz9zqyaCtl/ksKC4K1OJBBaQdI1cLr3xxSLavcFlbTEyDLEEgZww1UvkGruLV6A=

  # Cloudflare purge
  - secure: "pQXksdhDIBCAw5J6nyexhjwLcmpyEj9/cJ0Hm0RPj9bIbbK1IOM23iN8PaMqxR3YtNTg2EODfM8mHdCqXjq9ocI+7i2xGqk0HvSniWHUB90cCyzR4Xqxu03LIbrFo9cehYnHsLNNjrYs67CDCMUGECO4sDnWcAk9KPLtzrXnmruqa2GxRc+Dd7ajI+ZhJiIMgHiGNipoBxJ+ym08gVXb/Feb5p+4o/ynQsU9pRIiLr1EX0XV3i5N0eo5NsV6D7Kb7mGerR8n2svMb28RliE0Q5H82PSDSwzpVN3OZbAGcZYuA08DSJaCAhkIBTejA/6+3bBcyvOedg7ggvKT1WyQz8su1tCc3LIqGVyGGLINAM074zCrdpz35+6UOCV4Rc9F10V4iD3xgLKOO7MZz3+CcGS5bkGzp3ebGTw/or8prR+OAU8bAhoz52n0MM4AwklFURR22gNaGHwuxsn6fXhbBS+NFxj3Fo14JZiryaWELC90fVaV/vCb8gGa02q8//lAxwNdyIRrUhvCxxBy1i1G70cNDucDk1BSWrgypZTKTDoo51x8iWZcwEfk4oEYBmNGcQWhbTIvBYTZse16JUGNkdgZ5YWCWNZtFXMX4GjeAq7S794hU97c9Dh3/5eNCtfsyuArGpM7cc9WbtRDDquSZHd6jbfbMm+HRsSwBGi58NU="
branches:
  only:
  - master
