rvm:
- 2.1.7
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
script: make travis
after_success: make travis_success
env:
  global:
  # GitHub Pages
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: j9hUCLbjQu6S/WsOJDyL3/ErccQS/tGK4VfKbAYrg0BYGp5RUdGEhjvCB6nhHZHbmKqFERKWuhJeXXTYoZg2RFE2jBqheDPYAp7H0Glu1gt4ev/+aEDI6/G69nOddfbFqDudRAHA2bpOGKbpsEcG9AI5pTGPEu0hyqL+KacpwK3Fl7ReyPGBLRcZ8XEHVH1+Dxaa2JgDZKx3yKWbRJbgJvYkufR/Kh1H84tAInLj0Yead+C1VZVsCfMwSm3LdNLWCzkMqqxoUERnKz+OpJHWLZtDPW94wEYEwx5C7u0jibtTSGImxCt8MUMm8HgnzvWzT/LOYwF7htQpvTHHboswPzGz/JXTCe8MqELWK6MNGFqOqw8VI1qzrCRAUeM32Q5EA9D5MihzTIcYzb0RbJkS41QWRb8BZ+0Xx00ygfHMEH1+9B1aZBz4IK5ap5jRylYDlIqffbxvHJcZRottJai303c2r/ZmSGJJjxh74MkKmCoFJcac0XRqYEhNd7PYhIOdan+DzSeiMd5K6wqwhAtcM2RpijyimQGkHaC6CyJavEWebIzD0a+gXrTpXEd1HmaFNUdpq8KyBcYBBT1HrMdoJT+7KTLgvea2CslCPzHroZftLz9zqyaCtl/ksKC4K1OJBBaQdI1cLr3xxSLavcFlbTEyDLEEgZww1UvkGruLV6A=

  # Cloudflare purge
  - CLOUDFLARE_EMAIL: chris@cmbuckley.co.uk
  - secure: g1O90JEpZLjin7nRrKczKBlsaVGusIdsZCOosquWj8qwU8xBUfHYHiCmC03567RP19QRVCShVxwtR7+Wa4LPWzhJir7eSwAZPd5Jj+95/RN3W+auCSO9OmShRTsmWQ5tCP6oFbKaSVGOn/HNYVLhYbT4XvuqpWtnN+/OYWLp8lPPDbEK7mVxboDmdyJBxlzTar0jSfxfhh32GXZIv8Ah3LqbPZxsD967laoUwsZTBkn4i2hhNjDfHqZoA8AbXntxN6oYopGQhznfo9sU65OGBXc7mgBBBjnF0ydt0MK4nz0dc9zp9eZ/+n6Ecgi5nE659fMwLDr/DS6F3mNCqLEfbTjgOZUpQb3PPTuHzTsOZVKeAfZntGROGdG1ysI2Mgp28M/Q9KU3aXf3bn2upLigkUzYQDtnjwfxTJqRGGmUEEOy420eB+hfsky0ROQUfxu1EpjS5bD8P2eb+KfI+TWpwB/h0BfOxjB5qJVzSzx9EOucrhr9Ux/ZUuKj16zOLF9qR4XBIrrWFoTfrSKKTDEAE4O6Dimk7NKvq6R8WtSRNe5hsaPDf6n47CzlRceu+RxeU8zpGwo/2hw1pucQIAp0Ca6JrCW0Vw1fgjIW7PYvjOejElQAGgvgfL7gvSpXKJheoFNO4mMqWxrIRuGIjrQCVy62zaSP39go/GcpPR/dC4M=
branches:
  only:
  - master
