rvm:
- 2.1.7
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
script: make travis
after_success: make travis_success
env:
  global:
  # GitHub Pages
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.com
  - secure: "Wb7AjnnRV7hjH0NwzBak+ieRvMU5fx8Elrko4nvLhTkGWw+xNUzE36SnRLdUAYs6svf1kTP0FXkzMvO94XAbTTGbSjKbzDuZDKfUHNQxkPtzomTmwjLGJoGWr/NU6Cmf9lwK7+DCIVZjR0IDNJnzhukJd/bbpOWzuIklq6gQikrOc8tXujmIKkefDfrMofHNMzQiybiGR5IsrPFgS+kA7yvkv2zKFz1v8fwVHu1Nso5N40s8ZeozZxh2605a1AUzXZkEPqlFoBkwbxscQJap1X2UerkG2TEoe7C4u6+bgjirriPjSFbloq1C5/hhzXmHJFMut6GGmiC93dEZ7m8LfGIi22oL+wPQ4pQLJAE2qgq97XgxomcS6MudVFc44ZM6KtMkO2LUSzPR9wI4ePQZuPGNU/MIk4KJR8xc8tIVkXufKIPGXpT+mZWxKULSDvxeDUH/cGOb9lpo/qnPeso+J/B3nTzDk2o5f59S5t0/JQy4pZNk8urN3w4vFiBk9c6FtO/NsyboKov6LXfQCdJF2EZcX/3zi4Ma23i+tiaYpqNbwGml8bG2KaNrYgU3myZO6sHf9v9m0I5PGzSHb3NwYSWlBqDeSyiefJdJH13SYfi9rLlWw1OzALnFreP1m1Ij8Ge9c3uUawV/utllOgItDVzvjI9vtDneoxowVzgA4EI="

  # Cloudflare purge
  - secure: "pQXksdhDIBCAw5J6nyexhjwLcmpyEj9/cJ0Hm0RPj9bIbbK1IOM23iN8PaMqxR3YtNTg2EODfM8mHdCqXjq9ocI+7i2xGqk0HvSniWHUB90cCyzR4Xqxu03LIbrFo9cehYnHsLNNjrYs67CDCMUGECO4sDnWcAk9KPLtzrXnmruqa2GxRc+Dd7ajI+ZhJiIMgHiGNipoBxJ+ym08gVXb/Feb5p+4o/ynQsU9pRIiLr1EX0XV3i5N0eo5NsV6D7Kb7mGerR8n2svMb28RliE0Q5H82PSDSwzpVN3OZbAGcZYuA08DSJaCAhkIBTejA/6+3bBcyvOedg7ggvKT1WyQz8su1tCc3LIqGVyGGLINAM074zCrdpz35+6UOCV4Rc9F10V4iD3xgLKOO7MZz3+CcGS5bkGzp3ebGTw/or8prR+OAU8bAhoz52n0MM4AwklFURR22gNaGHwuxsn6fXhbBS+NFxj3Fo14JZiryaWELC90fVaV/vCb8gGa02q8//lAxwNdyIRrUhvCxxBy1i1G70cNDucDk1BSWrgypZTKTDoo51x8iWZcwEfk4oEYBmNGcQWhbTIvBYTZse16JUGNkdgZ5YWCWNZtFXMX4GjeAq7S794hU97c9Dh3/5eNCtfsyuArGpM7cc9WbtRDDquSZHd6jbfbMm+HRsSwBGi58NU="
branches:
  only:
  - master
