title: Chris Buckley
description: Chris Buckley's personal Web site
host: 0.0.0.0

url: https://cmbuckley.co.uk
baseurl: "/research"

repository: cmbuckley/research
remote_theme: "cmbuckley/cmbuckley.github.io"

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: assets
    values:
      exclude: true

exclude:
  - Makefile
  - vendor
