name: Purge Cloudflare Cache
on: page_build
jobs:
  purge_cache:
    name: Purge Cloudflare Cache
    runs-on: ubuntu-latest
    steps:
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        PURGE_URLS: '["https://cmbuckley.co.uk/research/","https://cmbuckley.co.uk/research/thesis.pdf"]'
