name: On Push
on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-assets:
    uses: cmbuckley/.github/.github/workflows/pages.yml@main
    secrets: inherit
    with:
      deploy_enabled: ${{ github.event_name == 'push' }}
      custom_commands: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra
        make
